### ISSUE TITLE
Depricated GetDataOnSessionKey() cannot be overloaded in cross-compiling

### ISSUE THREAD

**Issue by kbh88zz** [smartdevicelink/sdl_core#2137]
### Bug Report
When building with some toolchain, all the new type of GetDataOnSessionKey() functions newly added throughout some classes are conflicting with old type of same function that has been declared as deprecated in 4.5.0

##### Reproduction Steps
1. Download latest version (4.5.0) from master branch
2. Build with ARM toolchain (like 'arm-none-linux-gnueabi')
3. And wait for compilation errors related to the overload

##### Expected Behavior
It should be successful even if it was built by other toolchains instead of x86_64

##### Observed Behavior
The compiler emitted errors against all functions of GetDataOnSessionKey().
It says that two different type of this function can not be overloaded

`In file included from /home/bhkwon/sdl/core/src/components/include/connection_handler/connection_handler.h:38:0,
                 from /home/bhkwon/sdl/core/src/components/connection_handler/src/connection.cc:38:
/home/bhkwon/sdl/core/src/components/include/protocol_handler/session_observer.h:255:19: error: 'virtual int32_t protocol_handler::SessionObserver::GetDataOnSessionKey(uint32_t, uint32_t*, std::list<int>*, transport_manager::DeviceHandle*) const' cannot be overloaded
   virtual int32_t GetDataOnSessionKey(
                   ^
/home/bhkwon/sdl/core/src/components/include/protocol_handler/session_observer.h:242:19: error: with 'virtual int32_t protocol_handler::SessionObserver::GetDataOnSessionKey(uint32_t, uint32_t*, std::list<int>*, uint32_t*) const'
   virtual int32_t GetDataOnSessionKey(uint32_t key,
                   ^
In file included from /home/bhkwon/sdl/core/src/components/connection_handler/src/connection.cc:38:0:
/home/bhkwon/sdl/core/src/components/include/connection_handler/connection_handler.h:194:30: error: 'virtual int32_t connection_handler::ConnectionHandler::GetDataOnSessionKey(uint32_t, uint32_t*, std::list<int>*, uint32_t*) const' cannot be overloaded
   DEPRECATED virtual int32_t GetDataOnSessionKey(`

##### OS & Version Information
* OS/Version: Ubuntu 14.04 LTS (build machine)
* SDL Core Version: 4.5.0
* Testing Against: NA

**Comment by mrapitis** [comment]
this issue can also be easily replicated on a raspberry pi.

**Comment by shoamano83** [comment]
Actually, this issue is reproduced without cross-compiling. I gave a build on 32-bit Ubuntu 16.04 and got the same error.

I think the root cause is that `transport_manager::DeviceHandle` (which is `size_t`) will be same as `uint32_t` on some 32-bit architectures, hence the two methods collides.

I see one of the methods is marked as DEPRECATED, so probably the fix will be to remove the deprecated one?

**Comment by mrapitis** [comment]
Agree with @shoamano83 Can we plan to remove the deprecated methods in the next release?  This issue breaks compiling the project on some architectures as the parameters used in both the deprecated / non-deprecated GetDataOnSessionKey methods match in size for some archs.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2288
